#@ load("@ytt:data", "data")
#@ load("_ytt.lib.yml", "labels")
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: #@ data.values.registry.app + "-service-account"
  namespace: #@ data.values.registry.namespace
  labels: #@ labels()
